name: Python Tests

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
    paths:
      - .github/workflows/python-test.yml
      - backend/**
      - frontend/**
      - ml_pipeline/**
      - integration_tests/**
      - requirements.txt

jobs:
  backend-tests:
    name: Backend tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend # ToDo: fix after #21
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up uv
        uses: astral-sh/setup-uv@v6
        with:
          python-version: "3.12"
          enable-cache: true

      - name: Install dependencies
        run: uv sync --group dev

      - name: Run tests
        run: uv run python -m pytest tests -q

  integration_tests:
    name: Integration tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up uv
        uses: astral-sh/setup-uv@v6
        with:
          python-version: "3.12"
          enable-cache: true

      - name: Run tests
        run: uv run --with pytest pytest integration_tests -q
