name: Python Tests

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
    paths:
      - .github/workflows/tests.yml
      - backend/**
      - frontend/**
      - ml_pipeline/**
      - integration_tests/**
      - requirements.txt

jobs:
  backend-tests:
    name: Backend tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Set up uv
        uses: astral-sh/setup-uv@v8.1.0
        with:
          python-version: "3.12"
          enable-cache: true

      - name: Install dependencies
        run: uv sync --group dev

      - name: Run tests
        run: uv run python -m pytest tests -q

  ml_pipeline-tests:
    name: ML pipeline tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Set up uv
        uses: astral-sh/setup-uv@v8.1.0
        with:
          python-version: "3.12"
          enable-cache: true

      - name: Create virtual environment
        run: uv venv

      - name: Install dependencies
        run: uv pip install -r requirements.txt

      - name: Run tests
        run: cd ml_pipeline && uv run pytest tests

  integration-tests:
    name: Integration tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Set up uv
        uses: astral-sh/setup-uv@v8.1.0
        with:
          python-version: "3.12"
          enable-cache: true

      - name: Run tests
        run: uv run --with pytest pytest integration_tests -q
